# latexmk configuration: pdflatex + bibtex, quiet, build in place.
$pdf_mode = 1;
$bibtex_use = 2;
$clean_ext = "bbl nav out snm synctex.gz run.xml bcf";
$pdflatex = "pdflatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S";
