"""The README is the Hugging Face dataset card, so it is checked like one.

On the Hub this file is the landing page and its YAML front matter drives the
dataset viewer. It is also the document a reader meets before the ledger or the
manuscript, which is why the numbers in it are checked against the same
generated macros the paper uses: a README that disagrees with `numbers.tex` is
the failure this project has already had twice, once in the manuscript and once
in the ledger.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
UPSTREAM_README = ROOT / "README_UPSTREAM.md"
NUMBERS = ROOT / "paper" / "numbers.tex"

MACRO_DEF = re.compile(r"\\newcommand\{\\(num[A-Za-z]+)\}\{([^}]*)\}")

#: Numbers the README states in prose, and the macro each one must agree with.
#: The macro's rendered value has to appear verbatim in the README, so a
#: regenerated number that moves shows up here rather than in a reader's notes.
PINNED = [
    "numInversionGainFseven",     # inversion gain at f=0.7
    "numInversionCostFzero",      # cost at f=0
    "numEvasionAccMedqa",         # gate-aware optimum, MedQA
    "numEvasionCoherentMedqa",
    "numEvasionQMedqa",
    "numEvasionChance",
    "numEvasionAccMmlu",
    "numEvasionCoherentMmlu",
    "numFloorGsmk",
    "numFloorWorst",
    "numMitigHardBandMean",
    "numMitigSoftBandMean",
    "numMitigRandBandMean",
    "numMitigBothBandMean",
    "numInversionGainNTen",
    "numInversionGainNTwenty",
    "numInversionGainNFifty",
    "numInversionGainNRange",
    "numInversionGainWeak",
    "numQhatBinaryMean",
    "numQhatMcMean",
    "numQhatOpenTextMean",
    "numSleeperDropReputation",
    "numSleeperDropAip",
    "numSybilCoherentAip",
    "numSybilDisagreeingAip",
    "numDiscardOracleBoolqFseven",
    # Task 9
    "numCostAipGated",
    "numCostAipTrustOnly",
    "numCostMajority",
    "numCostGeometricMedian",
    "numCostGateOverheadPct",
    "numCompletionTokensMean",
    "numCostInferenceRatio",
    "numCompAccVsNeff",
    "numCompNeffVsAccMean",
    "numCompAccVsAccMean",
    "numCompSubsetsThree",
    "numCompSubsetsFive",
    "numAucLogprob",
    "numAucSelfReport",
    "numAucSelfReportFalsified",
    "numAucCellsPowered",
    "numAucBelowChanceCells",
]


def macros() -> dict[str, str]:
    return dict(MACRO_DEF.findall(NUMBERS.read_text(encoding="utf-8")))


def front_matter() -> dict:
    text = README.read_text(encoding="utf-8")
    assert text.startswith("---\n"), (
        "README.md must open with YAML front matter -- it is the Hugging Face "
        "dataset card and the Hub parses this block"
    )
    end = text.index("\n---\n", 3)
    return yaml.safe_load(text[4:end])


class TestDatasetCard:
    def test_front_matter_parses(self) -> None:
        meta = front_matter()
        assert meta["license"] == "mit"
        assert meta["pretty_name"]
        assert meta["tags"]

    def test_every_viewer_config_resolves_to_files(self) -> None:
        """A `configs:` entry pointing at nothing renders an empty viewer."""
        for config in front_matter()["configs"]:
            name = config["config_name"]
            for split in config["data_files"]:
                matches = list(ROOT.glob(split["path"]))
                assert matches, (
                    f"dataset config {name!r} points at {split['path']!r}, "
                    "which matches no file in the repository"
                )

    def test_config_names_are_unique(self) -> None:
        names = [c["config_name"] for c in front_matter()["configs"]]
        assert len(names) == len(set(names))


class TestReadmeAgreesWithGeneratedNumbers:
    @pytest.mark.parametrize("macro", PINNED)
    def test_number_appears(self, macro: str) -> None:
        defined = macros()
        assert macro in defined, f"{macro} is no longer generated by make_numbers.py"
        value = defined[macro].lstrip("+")
        # The README uses a typographic minus (U+2212) in prose; numbers.tex
        # emits ASCII. Normalise rather than forcing the README to look wrong.
        # Generated H100 macros belong to the preserved historical card.
        # The DGX card links separately measured outcomes and their provenance.
        text = UPSTREAM_README.read_text(encoding="utf-8").replace("\u2212", "-")
        assert value in text, (
            f"README_UPSTREAM.md does not contain {value!r} for {macro}. The generated "
            "number moved and the README was not updated with it."
        )


def test_paths_named_in_the_readme_exist() -> None:
    """Backticked repository paths in the README must be real."""
    text = README.read_text(encoding="utf-8")
    candidates = set(re.findall(r"`([A-Za-z0-9_./-]+/[A-Za-z0-9_./-]*)`", text))
    skipped = {"1/(C", "n/a"}
    missing = sorted(
        c for c in candidates
        if c not in skipped
        and not c.startswith(("http", "<", "https"))
        and "*" not in c
        and not (ROOT / c).exists()
    )
    assert not missing, f"README names paths that do not exist: {missing}"
