"""Honest/Byzantine assignment and swarm composition.

Which agents are adversarial, and which cached model each honest agent replays.
Both are drawn from a seeded generator so a sweep cell is reproducible from its
config alone.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True, slots=True)
class SwarmAssignment:
    """One realisation of a swarm: who is Byzantine, and who replays what."""

    n_agents: int
    byzantine: frozenset[int]
    models: tuple[str | None, ...]
    """``models[i]`` is the cached model an honest agent replays, or ``None`` for
    a Byzantine agent whose answer is generated by an adversary instead."""
    composition: str

    @property
    def honest(self) -> tuple[int, ...]:
        return tuple(i for i in range(self.n_agents) if i not in self.byzantine)

    @property
    def f_realised(self) -> float:
        return len(self.byzantine) / self.n_agents


def assign_swarm(
    n_agents: int,
    f: float,
    composition: list[str],
    rng: np.random.Generator,
    composition_name: str | None = None,
) -> SwarmAssignment:
    """Draw a swarm with a Byzantine fraction ``f``.

    The count is ``round(f * n)``, so the realised fraction is reported rather
    than assumed -- at ``N = 10`` every requested ``f`` is exact, but the field
    keeps the sweep honest if ``N`` ever changes.

    Honest agents are assigned models round-robin over ``composition`` after a
    shuffle, which keeps a mixed swarm balanced instead of leaving the balance to
    chance.
    """
    n_byz = int(round(f * n_agents))
    n_byz = max(0, min(n_agents, n_byz))
    byz = (
        frozenset(rng.choice(n_agents, size=n_byz, replace=False).tolist())
        if n_byz
        else frozenset()
    )

    honest = [i for i in range(n_agents) if i not in byz]
    order = rng.permutation(len(honest))
    models: list[str | None] = [None] * n_agents
    for slot, honest_index in enumerate(order):
        models[honest[int(honest_index)]] = composition[slot % len(composition)]

    return SwarmAssignment(
        n_agents=n_agents,
        byzantine=byz,
        models=tuple(models),
        composition=composition_name or "+".join(composition),
    )
